---
title: "generate_MR_reports"
author: "Marina Vabistsevits"
date: "20/06/2020"
output: html_document
---


```{r, warning=FALSE, include=FALSE, message=F}
# set path for pre-calculated data, outside the code repo
# `local` / `remote` (reading data from RDSF)
currently_working_env = "local"
source("set_paths.R")
set_paths(currently_working_env)

# metadata file
data_lookup<-readr::read_csv(paste0("metadata/data_lookup.csv"))

library(dplyr)
```


```{r}
# Function for running MR report generation 
renderMRreport = function(outputDir, mediator_name, breastcancer_dataset,  nameFile){
  
  rmarkdown::render(
    input = "MRreport.Rmd",
    output_format = "html_document",
    output_dir = outputDir,
    params = list(
      mediator_name = mediator_name,
      breastcancer_dataset = breastcancer_dataset
    ),
    run_pandoc = TRUE,
    output_file = paste0(outputDir,"/",nameFile)
  )
}
```


```{r}
current_trait_categoty <- "physical_traits"
data_lookup_sub <- data_lookup %>% 
                    filter(trait_category == current_trait_categoty,
                            format %in% c("tsv", "mrbase") )
mediator_list <- data_lookup_sub$trait

mediator_list <- mediator_list[6] # try just one


for (mediator in mediator_list){ 
  # Run the report generation
  print(paste0("Generating report for ", mediator))
  mediator_file_name <- data_lookup_sub %>% filter(trait == mediator) %>% pull(trait_file_name)
  
  renderMRreport(
               mediator_name = mediator,
               breastcancer_dataset ="ieu-a-1126", # default; only option currently accepted
               outputDir = paste0("MRreports/",current_trait_categoty, "/"), # inside codebase
               nameFile = paste0("MRreport_", mediator_file_name,"_", "ieu-a-1126", ".html")
               )
  
  print(paste0("Saved to: ", paste0("MRreports/",current_trait_categoty, "/", "MRreport_", mediator,".html")))
}

```



