---
title: "combine outputs from MR reports"
author: "Marina Vabistsevits"
date: "15/08/2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)

library(tidyr)
library(purrr)
library(tibble)
library(dplyr)
```

```{r message=F}
# set path for pre-calculated data, outside the code repo
# `local` / `remote` (reading data from RDSF)
currently_working_env = "local"
source("../set_paths.R")
set_paths(currently_working_env)

# metafile
data_lookup<-read_csv(paste0("../metadata/data_lookup.csv")) 

# load functions
source("../functions.R")

# breast cancer dataset
# 1126 full, 1127 ER+, 1128 ER-
breast_cancer_id <- "ieu-a-1126" 
bc_data <- stringr::str_split(breast_cancer_id, "-")[[1]][3]
```


```{r}
# specify group to process if data is in textfiles
current_trait_category <- "hormones"
mediators <- data_lookup %>% filter(trait_category == current_trait_category) %>% filter(!is.na(full_data)) %>%  filter(!grepl( "meno", trait_file_name)) %>% pull(trait_file_name) 
mediators

# specify group to process  if the data is in MRBase
current_trait_category <- "reproductive_traits"
mediators <- data_lookup %>% filter(trait_category == current_trait_category) %>% filter(!is.na(mrbase.id)) %>%  pull(trait_file_name)

current_trait_category <- "glycemic_traits"
mediators <- data_lookup %>% filter(trait_category == current_trait_category)  %>%  pull(trait_file_name)

```



```{r, message =F}
# run this once (all categories will be stored in a list)
all_traits_step1 <-list()
all_traits_step2 <-list()


# run things below fro each categoty separately
step1_all<-data.frame()
step2_all<-data.frame()

for (med in mediators){
  
  med_path <- paste0(results_path, current_trait_category, "/",med, "/") 
  report_path <- list.files(path = med_path, pattern = "report_", full.names = T)
  # select last report
  if ( length(report_path) > 1) {report_path<-report_path[-1]}
  
  ## step 1
  step1_file <- paste0(report_path, "/MR_BMI-to-", med,".tsv")
  print(paste0("reading: ", step1_file))
  mr_step1<-read_tsv(step1_file) %>% filter(exposure == "Childhood BMI")
  step1_all<- rbind(step1_all,mr_step1 )
  
  ## step 2
  step2_file <- paste0(report_path, "/MR_", med,"-to-BC.tsv")
  print(paste0("reading: ", step2_file))
  mr_step2<-read_tsv(step2_file) 
  step2_all<- rbind(step2_all,mr_step2 )
}
step1_all<-step1_all %>% arrange(outcome)
step2_all<-step2_all %>% arrange(exposure)

all_traits_step1[[current_trait_category]] <-step1_all
all_traits_step2[[current_trait_category]] <-step2_all
```


```{r}
step1_df<-purrr::reduce(all_traits_step1, full_join) %>% select(-c("or" , "or_lci95", "or_uci95"))
step2_df<-purrr::reduce(all_traits_step2, full_join) %>% select(-c("b", "se", "lo_ci", "up_ci", "id.outcome"))

write_tsv(step1_df, paste0(results_path, "_merged_results/", "step1_all_results.tsv"))
write_tsv(step2_df, paste0(results_path, "_merged_results/", "step2_all_results.tsv"))
```


